run:
  # Timeout for analysis, e.g. 30s, 5m.
  # Default: 1m
  timeout: 5m

linters:
  enable:
    # Checks for non-ASCII identifiers
    - asciicheck
    # Computes and checks the cyclomatic complexity of functions.
    - gocyclo
    # Inspects source code for security problems.
    - gosec

issues:
  # Disable max issues per linter.
  max-issues-per-linter: 0
  # Disable max same issues.
  max-same-issues: 0
  # Allow more permissive file permissions on the generated scrape target file only.
  exclude-rules:
  - path: cmd/config-generator/app/generator.go
    text: "G306: Expect WriteFile permissions to be 0600 or less"
    linters:
    - gosec
